let movieData = [
  {
    id : 0,
    title : "아무도 없는 곳",
    posterImg : "/assets/posterImg1.svg",
    open :  true,
    summary : "어느 이른 봄, 7년 만에 서울로 돌아온 소설가 ‘창석’이 우연히 만나고 헤어진 여기, 길 잃은 마음의 이야기",
    direct : "최재윤" 
  },
  {
    id : 1,
    title : "꿈의 제인",
    posterImg : "/assets/posterImg2.svg",
    open :  true,
    summary : "어느 날, 꿈결처럼 미스터리한 여인 '제인'이 나타나고, 그날 이후 소현은 조금씩 ‘제인’과의 시시한 행복을 꿈꾸기 시작한다.",
    direct : "조현훈"
  },
  {
    id : 2,
    title : "어른들은 몰라요",
    posterImg : "/assets/posterImg3.svg",
    open :  true,
    summary : "“우리도 살아야 되잖아요.” 어른들은 모르는 가장 솔직한 10대들의 이야기",
  },
  {
    id : 3,
    title : "아워 바디",
    posterImg : "/assets/posterImg4.svg",
    open :  true,
    summary : "아워 바디 입니다.",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 4,
    title : "우리집",
    posterImg : "/assets/posterImg5.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 5,
    title : "애연",
    posterImg : "/assets/posterImg6.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 6,
    title : "아이",
    posterImg : "/assets/posterImg7.svg",
    open :  true,
    summary : "누구보다 강한 생활력으로 하루하루 살아온 아동학과 졸업반의 보호종료아동 ‘아영’(김향기) 돈이 필요했던 ‘아영’은 생후 6개월 된 아들 ‘혁’이를 홀로 키우는 워킹맘이자 초보 엄마 ‘영채’(류현경)의 베이비시터가 된다. 조금 부족하지만 어떻게든 자신의 힘으로 ‘혁’이를 키우고자 하는 ‘영채’는 자신보다 더 ‘혁’이를 살뜰히 돌보는 ‘아영’의 모습에 어느새 안정을 되찾고 평범한 삶을 꿈꾸기 시작한다. 하지만 어느 날, ‘혁’이에게 사고가 난다. ‘영채’는 모든 책임을 ‘아영’의 탓으로 돌리고, 다시 ‘혁’이와 둘만 남게 된 ‘영채’는 고단한 현실에 어쩔 수 없는 선택을 하게 된다. 이를 알게 된 ‘아영’은 ‘혁’이를 다시 ‘영채’의 품에 돌려놓기 위해 애를 쓰는데...",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 7,
    title : "여자들",
    posterImg : "/assets/posterImg8.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 8,
    title : "우리들",
    posterImg : "/assets/posterImg9.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 9,
    title : "님아 그강을 건너지마오",
    posterImg : "/assets/posterImg10.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 10,
    title : "워낭소리",
    posterImg : "/assets/posterImg11.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 11,
    title : "스타박'스 다방",
    posterImg : "/assets/posterImg12.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 12,
    title : "윤희에게",
    posterImg : "/assets/posterImg13.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 13,
    title : "돼지의 왕",
    posterImg : "/assets/posterImg14.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 14,
    title : "노무현입니다",
    posterImg : "/assets/posterImg15.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 15,
    title : "소공녀",
    posterImg : "/assets/posterImg16.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 16,
    title : "박화영",
    posterImg : "/assets/posterImg17.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 17,
    title : "기도하는 남자",
    posterImg : "/assets/posterImg18.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 18,
    title : "똥파리",
    posterImg : "/assets/posterImg19.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 19,
    title : "한공주",
    posterImg : "/assets/posterImg20.svg", 
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ",, "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 20,
    title : "휴가",
    posterImg : "/assets/posterImg21.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 21,
    title : "10월의 이름들",
    posterImg : "/assets/posterImg22.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 22,
    title : "강변호텔",
    posterImg : "/assets/posterImg23.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 23,
    title : "그들이 죽었다",
    posterImg : "/assets/posterImg24.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 24,
    title : "들개",
    posterImg : "/assets/posterImg25.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 25,
    title : "메기",
    posterImg : "/assets/posterImg26.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
  {
    id : 26,
    title : "메멘토모리",
    posterImg : "/assets/posterImg27.svg",
    open :  true,
    summary : "",
    releaseDate: "2023.18.24",
    director: "문지욱",
    screenplay: "장재영",
    cast: ["문지욱 ", "장재영 ", "서태성 ", "최재윤 ", "장준우 ", "권수빈 ", "안슬민 ", "임현준 ", "송현민 "],
  },
]

export default movieData;
