let movieData = [
  {
    id : 0,
    title : "아무도 없는 곳",
    posterImg : "/assets/posterImg1.svg",
    open :  true,
    summary : "어느 이른 봄, 7년 만에 서울로 돌아온 소설가 ‘창석’이 우연히 만나고 헤어진 여기, 길 잃은 마음의 이야기",
    date : "개봉일 : " ,
    direct : "감독 : ",
    scirpt : "각본 : ",
    act : "출연진 : ", 
  },
  {
    id : 1,
    title : "꿈의 제인",
    posterImg : "/assets/posterImg2.svg",
    open :  true,
    summary : "",
  },
  {
    id : 2,
    title : "어른들은 몰라요",
    posterImg : "/assets/posterImg3.svg",
    open :  true,
    summary : "",
  },
  {
    id : 3,
    title : "아워 바디",
    posterImg : "/assets/posterImg4.svg",
    open :  true,
    summary : "",
  },
  {
    id : 4,
    title : "우리집",
    posterImg : "/assets/posterImg5.svg",
    open :  true,
    summary : "",
  },
  {
    id : 5,
    title : "애연",
    posterImg : "/assets/posterImg6.svg",
    open :  true,
    summary : "",
  },
  {
    id : 6,
    title : "아이",
    posterImg : "/assets/posterImg7.svg",
    open :  true,
    summary : "",
  },
  {
    id : 7,
    title : "여자들",
    posterImg : "/assets/posterImg8.svg",
    open :  true,
    summary : "",
  },
  {
    id : 8,
    title : "우리들",
    posterImg : "/assets/posterImg9.svg",
    open :  true,
    summary : "",
  },
  {
    id : 9,
    title : "님아 그강을 건너지마오",
    posterImg : "/assets/posterImg10.svg",
    open :  true,
    summary : "",
  },
  {
    id : 10,
    title : "워낭소리",
    posterImg : "/assets/posterImg11.svg",
    open :  true,
    summary : "",
  },
  {
    id : 11,
    title : "스타박'스 다방",
    posterImg : "/assets/posterImg12.svg",
    open :  true,
    summary : "",
  },
  {
    id : 12,
    title : "윤희에게",
    posterImg : "/assets/posterImg13.svg",
    open :  true,
    summary : "",
  },
  {
    id : 13,
    title : "돼지의 왕",
    posterImg : "/assets/posterImg14.svg",
    open :  true,
    summary : "",
  },
  {
    id : 14,
    title : "노무현입니다",
    posterImg : "/assets/posterImg15.svg",
    open :  true,
    summary : "",
  },
  {
    id : 15,
    title : "소공녀",
    posterImg : "/assets/posterImg16.svg",
    open :  true,
    summary : "",
  },
  {
    id : 16,
    title : "박화영",
    posterImg : "/assets/posterImg17.svg",
    open :  true,
    summary : "",
  },
  {
    id : 17,
    title : "기도하는 남자",
    posterImg : "/assets/posterImg18.svg",
    open :  true,
    summary : "",
  },
  {
    id : 18,
    title : "똥파리",
    posterImg : "/assets/posterImg19.svg",
    open :  true,
    summary : "",
  },
  {
    id : 19,
    title : "한공주",
    posterImg : "/assets/posterImg20.svg", 
    open :  true,
    summary : "",
  },
  {
    id : 20,
    title : "휴가",
    posterImg : "/assets/posterImg21.svg",
    open :  true,
    summary : "",
  },
  {
    id : 21,
    title : "10월의 이름들",
    posterImg : "/assets/posterImg22.svg",
    open :  true,
    summary : "",
  },
  {
    id : 22,
    title : "강변호텔",
    posterImg : "/assets/posterImg23.svg",
    open :  true,
    summary : "",
  },
  {
    id : 23,
    title : "그들이 죽었다",
    posterImg : "/assets/posterImg24.svg",
    open :  true,
    summary : "",
  },
  {
    id : 24,
    title : "들개",
    posterImg : "/assets/posterImg25.svg",
    open :  true,
    summary : "",
  },
  {
    id : 25,
    title : "메기",
    posterImg : "/assets/posterImg26.svg",
    open :  true,
    summary : "",
  },
  {
    id : 26,
    title : "메멘토모리",
    posterImg : "/assets/posterImg27.svg",
    open :  true,
    summary : "",
  },
]

export default movieData;
